services:
  shopping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:8080"

  shopping.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:8080"

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

