name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker Image
      run: docker build -f Shopping/Shopping.Client/Dockerfile -t tanpham28/shoppingclient:latest ./Shopping/Shopping.Client
      
    - name: Push Docker Image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push tanpham28/shoppingclient:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: xuantanweb
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: tanpham28/shoppingclient:latest
