name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: build image
      run: docker build -f Shopping/Shopping.Client/Dockerfile -t tanpham28/shoppingclient:latest ./Shopping/Shopping.Client
      
    - name: push image to docker hub
      run: |
          docker login -u tanpham28 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push tanpham28/shoppingclient:latest
