# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shoppingappweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5ca94d45d963446bad732e6dc0a6c443 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6174a6e0a85d45aea96bb70e01c5365e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5ca94d45d963446bad732e6dc0a6c443 }}/tanpham28/shoppingclient:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shoppingappweb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30b7f23fee264a7b9db0acb39e16a8fd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5ca94d45d963446bad732e6dc0a6c443 }}/tanpham28/shoppingclient:${{ github.sha }}'